Numpy
- convert a list,tuple,dict into array
- how to generate array with in a range of values
    - arange
    - linspace
    - random .randint
- basic arthimetic operators on numpy array

In [83]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
#how to slicing
print(a[1:10])
print(a[1:10:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [85]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [86]:
#fancy indexing or boolean indexing:
# we will get the values for which it is true

print(a[a>5])

[6 7 8 9]


In [87]:
# to check the shape of an array:
a.shape

(10,)

In [88]:
# to check the dimensional of an array:

a.ndim

1

In [89]:
# to create a two dimensional array:
# 10,30 is the range and 3,4 is rows and columns:

a2 = np.random.randint(10,30,(3,4))
a2

array([[23, 11, 17, 15],
       [24, 21, 25, 27],
       [16, 24, 17, 20]])

In [90]:
a2.ndim

2

In [91]:
#it will print row  wise:

for i in a2:
    print(i)
    break

[23 11 17 15]


In [92]:
# to acess element wise :

for i in a2:
    for j in i:
        print(j,end=",")
    print()

23,11,17,15,
24,21,25,27,
16,24,17,20,


In [93]:
#slicing for an array:

print(a2[1],type(a2[1]),a2[1].shape)

[24 21 25 27] <class 'numpy.ndarray'> (4,)


In [94]:
# slicing from 2 column:

print(a2[1:],type(a2[1:]))

[[24 21 25 27]
 [16 24 17 20]] <class 'numpy.ndarray'>


In [95]:
a2

array([[23, 11, 17, 15],
       [24, 21, 25, 27],
       [16, 24, 17, 20]])

In [96]:
# rows from 0 to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2]) #  or print(a2[1,2])

25


In [97]:
print(a2[1:3])

[[24 21 25 27]
 [16 24 17 20]]


In [98]:
print(a2[0::1])

[[23 11 17 15]
 [24 21 25 27]
 [16 24 17 20]]


In [99]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[49, 90, 73],
        [12, 24, 18],
        [12, 74, 19],
        [49, 84, 97],
        [38, 41, 17]],

       [[82, 12, 35],
        [68, 76, 40],
        [10, 33, 29],
        [33, 12, 50],
        [43, 46, 94]],

       [[63, 77, 14],
        [81, 98, 31],
        [92, 70, 73],
        [53, 14, 58],
        [24, 58, 48]],

       [[35, 99, 57],
        [74, 79, 17],
        [73, 14, 84],
        [99, 69, 22],
        [52, 59, 62]],

       [[25, 50, 62],
        [93, 92, 68],
        [60, 70, 99],
        [23, 35, 28],
        [18, 96, 52]]])

In [100]:
print(a3[:2]) # indices -0-1

[[[49 90 73]
  [12 24 18]
  [12 74 19]
  [49 84 97]
  [38 41 17]]

 [[82 12 35]
  [68 76 40]
  [10 33 29]
  [33 12 50]
  [43 46 94]]]


In [101]:
print(a3[1::2])

[[[82 12 35]
  [68 76 40]
  [10 33 29]
  [33 12 50]
  [43 46 94]]

 [[35 99 57]
  [74 79 17]
  [73 14 84]
  [99 69 22]
  [52 59 62]]]


In [102]:
print(a3)

[[[49 90 73]
  [12 24 18]
  [12 74 19]
  [49 84 97]
  [38 41 17]]

 [[82 12 35]
  [68 76 40]
  [10 33 29]
  [33 12 50]
  [43 46 94]]

 [[63 77 14]
  [81 98 31]
  [92 70 73]
  [53 14 58]
  [24 58 48]]

 [[35 99 57]
  [74 79 17]
  [73 14 84]
  [99 69 22]
  [52 59 62]]

 [[25 50 62]
  [93 92 68]
  [60 70 99]
  [23 35 28]
  [18 96 52]]]


In [103]:
print(a3[1::2,0:5:2])

[[[82 12 35]
  [10 33 29]
  [43 46 94]]

 [[35 99 57]
  [73 14 84]
  [52 59 62]]]


In [104]:
# boolean indexing:
a3[a3==80]

array([], dtype=int32)

In [105]:
a3[a3>50]

array([90, 73, 74, 84, 97, 82, 68, 76, 94, 63, 77, 81, 98, 92, 70, 73, 53,
       58, 58, 99, 57, 74, 79, 73, 84, 99, 69, 52, 59, 62, 62, 93, 92, 68,
       60, 70, 99, 96, 52])

In [106]:
a3[(a3>50) & (a3<70)]

array([68, 63, 53, 58, 58, 57, 69, 52, 59, 62, 62, 68, 60, 52])

In [107]:
a3[(a3>50)| (a3<70)]

array([49, 90, 73, 12, 24, 18, 12, 74, 19, 49, 84, 97, 38, 41, 17, 82, 12,
       35, 68, 76, 40, 10, 33, 29, 33, 12, 50, 43, 46, 94, 63, 77, 14, 81,
       98, 31, 92, 70, 73, 53, 14, 58, 24, 58, 48, 35, 99, 57, 74, 79, 17,
       73, 14, 84, 99, 69, 22, 52, 59, 62, 25, 50, 62, 93, 92, 68, 60, 70,
       99, 23, 35, 28, 18, 96, 52])

In [108]:
l=list(range(10))
print(l[:])
print(l[1:])
print(l[1::2])


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


In [109]:
l[[1,13,45,74,23,67]]

TypeError: list indices must be integers or slices, not list

In [110]:
al=np.array(l)
al[[1,13,45,74,23,67]]

IndexError: index 13 is out of bounds for axis 0 with size 10

In [111]:
a2

array([[23, 11, 17, 15],
       [24, 21, 25, 27],
       [16, 24, 17, 20]])

In [112]:
a2[[1,2],[0,1]]


array([24, 24])

In [113]:
a3

array([[[49, 90, 73],
        [12, 24, 18],
        [12, 74, 19],
        [49, 84, 97],
        [38, 41, 17]],

       [[82, 12, 35],
        [68, 76, 40],
        [10, 33, 29],
        [33, 12, 50],
        [43, 46, 94]],

       [[63, 77, 14],
        [81, 98, 31],
        [92, 70, 73],
        [53, 14, 58],
        [24, 58, 48]],

       [[35, 99, 57],
        [74, 79, 17],
        [73, 14, 84],
        [99, 69, 22],
        [52, 59, 62]],

       [[25, 50, 62],
        [93, 92, 68],
        [60, 70, 99],
        [23, 35, 28],
        [18, 96, 52]]])

In [114]:
print(a3[[1,2],[1,2],[1,2]])
print(a3[1,1,1])
print(a3[2,2,2])

[76 73]
76
73


In [115]:
#statistical Functions:


In [124]:
a=np.random.randint(20,30,5)
a

array([23, 27, 25, 28, 28])

In [125]:
# to calculate the mean of the array:
print(np.mean(a))
print(np.sum(a)/np.size(a))

26.2
26.2


In [129]:
# sorting  
sorted(a)

[23, 25, 27, 28, 28]

In [130]:
#median is calculated after sorting :
np.median(a)

27.0

In [133]:
# Quantile:

print(np.quantile(a,0.25)) #Q1(median of first half)
print(np.quantile(a,0.5))  #Q2(median of second half)
print(np.quantile(a,0.75)) #Q3(median of last part)


25.0
27.0
28.0


In [135]:
# logarithms and exponential operators:

In [143]:
print(np.log(2))  # log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [147]:
print(np.log2(2))
print(np.log10(5))
print(np.log2(7))

1.0
0.6989700043360189
2.807354922057604


In [145]:
np.log(0)



D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf